name: Release

env:
  SCRIPT_MINIFIED = minified.js
  SCRIPT_BLOB_URL = "https://github.com/SimonLammer/anki-persistence/blob/${GITHUB_SHA}"

on:
  push:
    branches-ignore: []

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: printf "// $VERSION - $GH_SCRIPT_URL\n" > ${SCRIPT_MINIFIED}
      - run: npm run minify | tail -n 1 >>${SCRIPT_MINIFIED}
      - run: cat ${SCRIPT_MINIFIED}

