name: Release

env:
  SCRIPT_MINIFIED: script_minified.js
  BLOB_URL_PREFIX: "https://github.com/SimonLammer/anki-persistence/blob"

on:
  workflow_run:
    workflows: ["Test"]
    branches-ignore: []
    types:
      - completed
  push:
    branches: [ci]

jobs:
  release:
    runs-on: ubuntu-latest
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'

      # Ensure version has been incremented
      - run: jq <package.json -r '.version' > version.txt

      # Minify script
      - run: printf "// `cat version.txt` - ${BLOB_URL_PREFIX}/${GITHUB_SHA}/script.js\n" >${SCRIPT_MINIFIED}
      - run: npm run minify | tail -n 1 >>${SCRIPT_MINIFIED}

      # Upload artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: release
          path: |
            version.txt
            script.js
            script_minified.js

      # Create release

