name: Release

env:
  SCRIPT_MINIFIED: script-minified.js
  BLOB_URL_PREFIX: "https://github.com/SimonLammer/anki-persistence/blob"

on:
  workflow_run:
    workflows: ["Test"]
    branches-ignore: []
    types:
      - completed
  push:
    branches: [ci]

jobs:
  release:
    runs-on: ubuntu-latest
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      # Fetch version numbers
      - uses: actions/checkout@v3
        with:
          ref: master
          path: master
      - run: jq <master/package.json -r '.version' >version-main.txt
      - run: jq <package.json -r '.version' >version-current.txt

      - uses: actions/setup-node@v3
        with:
          cache: 'npm'

      - name: Minify script.js
        run: |
          printf "// `cat version-current.txt` - ${BLOB_URL_PREFIX}/${GITHUB_SHA}/script.js\n" >${SCRIPT_MINIFIED}
          npm run minify | tail -n 1 >>${SCRIPT_MINIFIED}

      - uses: actions/upload-artifact@v3
        with:
          name: release
          path: |
            version-main.txt
            version-current.txt
            script.js
            script-minified.js

      - name: Ensure version number has been incremented
        run: node -e '
          const fs=require("fs");
          function r(f){
            return fs.readFileSync(f).toString().trim().split(".").map(Number);
          };
          c=r("version-current.txt");
          m=r("version-main.txt");
          for (i in m) {
            if(c[i]>m[i])
              break;
            assert(c[i]==m[i], "Current version is lower than master version")
          };
          assert(i<m.length-1||c[i]>m[i], "Current version number equals master version number");'

      # Create release

